# Generated by Django 2.1.5 on 2019-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_emailvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='userfiles',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
